### ISSUE TITLE
Sidekick or Modified Influxdb version ?

### ISSUE THREAD

**Issue by AlexGrs** [adamringhede/influxdb-ha#1]
Hello !

I was just wondering if this program is . sidekick we should run alongside any InfluxDB nodes or this is a modified version of InfluxDB that we need to use our existing node ?

Thanks.

**Comment by adamringhede** [comment]
@AlexGrs This is meant to run alongside InfluxDB on the same machine for each node. You can see how it is done in the example Kubernetes setup found in the directory called "kubernetes"
